### ISSUE TITLE
Not working with the latest version on Angular-cli (beta.17)

### ISSUE THREAD

**Issue by jculverwell** [WoltersKluwerPL/ng-spin-kit#23]
Thank you for a great library.  

I am getting the error below when I am using version 1.1.0 together with the latest version of Angular-CLI (beta.17)

```
metadata_resolver.js:700Uncaught Error: moduleId should be a string in "RotatingPlaneComponent". See https://goo.gl/wIDDiL for more information.
If you're using Webpack you should inline the template and the styles, see https://goo.gl/X2J8zc.
```

My project is very vanilla, I just created a new angular-cli project and then added ng2-spin-kit using the code from the readme.md.

Welcome your thoughts?

**Comment by mrzepinski** [comment]
@jculverwell Thanks for your feedback ;)

Could you show your code here?

In each component, template and styles are inline. I didn't test components in angular-cli project, but I think that the most important is configuration in your project. Which module bundler do you use?

**Comment by jgr3go** [comment]
I get this same issue during runtime when using webpack.  

```
// app.module.ts 

...
import * as spinner from 'ng2-spin-kit/app/spinners';

@NgModule({
  declarations: [ 
    spinner.FadingCircleComponent,
    ...
```

I'm not actually using it anywhere in html yet, but the import/declaration results in the above error.  Removing the `moduleId: module.id` line from the component fixes it, but I'm not positive what that's going to do elsewhere.

**Comment by fbarbat** [comment]
+1

**Comment by rodneyjoyce** [comment]
Yes, I have the same problem with Angular-CLI .21

The hack was to remove the   moduleId: module.id from the spinner component in the Node module folder as mentioned above.

**Comment by mrzepinski** [comment]
@rodneyjoyce In `ng2-spin-kit` there is not moduleId in the code. It was before, but newer versions don't have it.

**Comment by rodneyjoyce** [comment]
Hmm that's odd, I thought I NPMed the latest package. Thanks
