### ISSUE TITLE
No working for angular 2.1.0

### ISSUE THREAD

**Issue by joelmuskwe** [WoltersKluwerPL/ng-spin-kit#24]
No working for angular 2.1.0 can you update it to the latest package

**Comment by mrzepinski** [comment]
@joelmuskwe Which version do you use? I've tested `1.1.0` with AJS 2.1.0

**Comment by alex88** [comment]
Here `1.1.0` doesn't work with `2.1.2`, I get `moduleId should be a string in "DoubleBounceComponent"`

**Comment by alex88** [comment]
Also I think your requirements are too strict

**Comment by fdagosti** [comment]
helo, any update on this problem ? I am also having the same problem, I guess the list of components need to be updated to the latest angular 2 version ?
thanks a lot

**Comment by mrzepinski** [comment]
@alex88 or @fdagosti Could you create your PR which will fix that?

**Comment by atais** [comment]
I can not import it in `Angular 2.2.2` either.

**Comment by mrzepinski** [comment]
@alex88 @fdagosti @atais I've tested ng2-spin-kit with `Angular 2.2.3` and everything works fine.

**Comment by atais** [comment]
@mrzepinski are you using it as a local library or imported with npm?

I am using this project as my boilerplate: https://github.com/preboot/angular2-webpack

When I add your Component in my module, fe:

```
(...)
import {FadingCircleComponent}  from 'ng2-spin-kit/app/spinners';

@NgModule({
  declarations: [
    FadingCircleComponent,
    ...
  ],
  providers: [...],
  imports: [...]
})
export class ReportsModule {
  constructor() {
  }
}
```

I receive an error when I try to start an app:

> Uncaught Error: Unexpected value 'FadingCircleComponent' declared by the module 'ReportsModule'(…)

And it differs in name, depending on what I part I try to import.
I think it is connected with #26 and maybe my webpack script does not compile your typescript library, but I am just starting with Angular 2 and it is hard to be sure.

**Comment by mrzepinski** [comment]
@atais Could you paste here your webpack configuration?

**Comment by atais** [comment]
It is nearly identical to: https://github.com/preboot/angular2-webpack/blob/master/webpack.config.js

I think it has something to do with 
```
      {
        test: /\.ts$/,
        loaders: ['awesome-typescript-loader?' + atlOptions, 'angular2-template-loader'],
        exclude: [isTest ? /\.(e2e)\.ts$/ : /\.(spec|e2e)\.ts$/, /node_modules\/(?!(ng2-.+))/],
      },
```

but simple change like this did not help :disappointed: 
```
      {
        test: /\.ts$/,
        loaders: ['awesome-typescript-loader?' + atlOptions, 'angular2-template-loader'],
        exclude: [isTest ? /\.(e2e)\.ts$/ : /\.(spec|e2e)\.ts$/, /node_modules\/(?!(ng2-.+))/],
        include: [/node_modules\/ng2-spin-kit/]
      },
```

**Comment by mrzepinski** [comment]
@atais You should try to change:

```
config.resolve = {
  // only discover files that have those extensions
  extensions: ['.ts', '.js', '.json', '.css', '.scss', '.html'],
};
```
to
```
config.resolve = {
  // only discover files that have those extensions
  extensions: ['.ts', '.js', '.json', '.css', '.scss', '.html'],
  // an array of directory names to be resolved to the current directory
  modules: [helpers.root('src'), helpers.root('node_modules')],
};
```
Give me a feedback then.

**Comment by atais** [comment]
@mrzepinski thanks, but unfortunately there is a next error:

```
Uncaught Error: moduleId should be a string in "FadingCircleComponent". See https://goo.gl/wIDDiL for more information. If you're using Webpack you should inline the template and the styles, see https://goo.gl/X2J8zc.
```

I really think it should fix itself with #26, I am working on PR.
Thanks.

**Comment by mrzepinski** [comment]
@atais `template` and `styles` are already included into component. There is not requirement for `moduleId`.

**Comment by atais** [comment]
@mrzepinski well... we know it but, but seems that webpack does not :smile:
