### ISSUE TITLE
Template parse errors

### ISSUE THREAD

**Issue by feurjarx** [WoltersKluwerPL/ng-spin-kit#25]
zone.js:388 Unhandled Promise rejection: Template parse errors:
'sk-circle' is not a known element:
1. If 'sk-circle' is an Angular component, then verify that it is part of this module.
2. If 'sk-circle' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
    [ERROR ->]<sk-circle></sk-circle>

**Comment by mrzepinski** [comment]
@feurjarx Which version of AngularJS 2.x do you have?
Could you reproduce the bug outside your project and paste snippet of code here?

**Comment by CodeContrive** [comment]
I also encountered this problem. Did anyone solve this?

**Comment by mrzepinski** [comment]
@CodeContrive Do you have the same problem with `1.2.0` version? Could you paste some code here?

**Comment by atais** [comment]
@feurjarx , @CodeContrive , did you declare it properly? 
fe:

```javascript
import {FadingCircleComponent} from 'ng2-spin-kit';

@NgModule({
  declarations: [
    FadingCircleComponent
  ]
})
export class ReportsModule {
  constructor() {
  }
}
```
