### ISSUE TITLE
Make ng-spin-kit AOT compliant

### ISSUE THREAD

**Issue by julienboulay** [WoltersKluwerPL/ng-spin-kit#29]
Hi,

First, thanks for these nice components.

I encountered an issue using the components with the latest angular-cli version v1.0.0-beta30.
It happens when running `ng build --target=production`

I get this error : 
```
ERROR in Unexpected value 'RotatingPlaneComponent in <projectdir>/node_modules/ng-spin-kit/dist/spinner/rotating-plane.component.d.ts' declared by the module 'AppModule in <projectdir>/src/app/app.module.ts'

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '<projectdir>/src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts
```

It seems to be related to AOT compilation.

**Comment by mrzepinski** [comment]
@julienboulay Hi :) Could you reproduce the error with the snippet of your code?

**Comment by julienboulay** [comment]
I simply declared the component in my module and used it in the template :

```
//app.module.ts
import { RotatingPlaneComponent } from 'ng-spin-kit';

@NgModule({
  declarations: [
    RotatingPlaneComponent,
    AppComponent
  ],
  imports: [
    BrowserModule,
    HttpModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

```
<!-- app.component.html-->
<sk-rotating-plane [isRunning]="true"></sk-rotating-plane>
```

It might require a NgSpinnerModule to import it like others modules

**Comment by mrzepinski** [comment]
@julienboulay It's related to: https://github.com/angular/angular-cli/issues/3674
Look at the comments which are there.

**Comment by mrzepinski** [comment]
@julienboulay Is it work right now with `3.0.0` version?

**Comment by julienboulay** [comment]
@mrzepinski not working with `3.0.0`

Now, I got this error : `ERROR in NgSpinKitModule is not an NgModule`

**Comment by mrzepinski** [comment]
@julienboulay Look at: https://angular.io/docs/ts/latest/guide/ngmodule.html#!#static-bootstrapping-with-the-ahead-of-time-aot-compiler

**Comment by julienboulay** [comment]
@mrzepinski : please have a look to https://medium.com/@cyrilletuzi/how-to-build-and-publish-an-angular-module-7ad19c0b4464#.zczwqckfv

To my point of view, this issue might be related to the packaging of the ng-spin-kit module and not about the way I compile the code.

**Comment by julienboulay** [comment]
I will try to make a PR on this point to.

**Comment by mrzepinski** [comment]
@julienboulay Thanks. I'm sorry that I'm not so involved, but recently I have a lot of private things on my mind.

**Comment by jderuere** [comment]
@julienboulay same problem.

Have you look at https://github.com/naaambo/ng2-spin-kit

**Comment by rannaot** [comment]
I have the same issues - 
ERROR in NgSpinKitModule is not an NgModule 
SO in general I made it such in the dist... js files

And now my AOT fails at similar error. Any solution ?
