### ISSUE TITLE
Create NgModule for importing spinner component to multiple modules of the same project

### ISSUE THREAD

**Issue by julienboulay** [WoltersKluwerPL/ng-spin-kit#30]
Please provive a NgSpinKitModule to be able to import a component in multiple module of the same project.
Otherwise, I get the following error : "RotatingPlaneComponent is part of the declarations of 2 modules:..."

It is linked to this issue : https://github.com/angular/angular/issues/10646

**Comment by mrzepinski** [comment]
@julienboulay Could you create PR?

**Comment by julienboulay** [comment]
@mrzepinski here is the new PR : https://github.com/WoltersKluwerPL/ng-spin-kit/pull/31

Thanks in advanced

**Comment by mrzepinski** [comment]
@julienboulay Thanks :)

Version `3.0.0` is available - https://github.com/WoltersKluwerPL/ng-spin-kit/releases/tag/3.0.0
