### ISSUE TITLE
Support different colors w/ input parameter or add details in readme about targeting child component colors.

### ISSUE THREAD

**Issue by gins0023** [WoltersKluwerPL/ng-spin-kit#32]
It's answered here, but not an obvious thing to know for targeting child component styles other than your own child components.

http://stackoverflow.com/questions/36527605/how-to-style-child-components-from-parent-components-css-file

sass version
`:host /deep/ sk-wave {
      .wave-spinner > div {
         background-color: #FFF !important;
       }
  }`

normal
`:host >>> sk-wave {
      .wave-spinner > div {
         background-color: #FFF !important;
       }
  }`

**Comment by gins0023** [comment]
btw, thanks for making this!

**Comment by mrzepinski** [comment]
@gins0023 What do you suggest? Can you prepare some PR with your solution?

**Comment by gins0023** [comment]
I don't have a problem w/ just updating the docs, but I can take a stab at PR sure.  I would probably refactor the code so all components extend from a base component to reduce a little of the boilerplate and render the child divs in a loop w/ ngStyle culled from either the passed in color or the default #333.

**Comment by mrzepinski** [comment]
@gins0023 Extending base component is not the best option. Each component will be dependent of another class. I had a lot of issues with this kind of implementation.
