### ISSUE TITLE
v5.1.0 needs publish to npm

### ISSUE THREAD

**Issue by spongessuck** [WoltersKluwerPL/ng-spin-kit#38]
5.1.0 is not yet available via npm.

**Comment by mrzepinski** [comment]
@spongessuck I have an error when `ngc` is running - it's related to unresolved https://github.com/angular/angular-cli/issues/3707

**Comment by spongessuck** [comment]
@mrzepinski When did you get this error? For me, NGC ran automatically after I did an `npm install` and didn't throw any errors.

Do you have a stack trace you can post?

**Comment by spongessuck** [comment]
@mrzepinski Never mind, I just cloned this repo and I'm getting errors on NGC. Stand by.

**Comment by spongessuck** [comment]
See #39 for a new PR that should fix it. The main issue was a missing `tsconfig.json` file.

**Comment by mrzepinski** [comment]
@spongessuck Thanks ;) `5.1.1` is available in NPM
