### ISSUE TITLE
Most recent version not available on NPM

### ISSUE THREAD

**Issue by mateuswetah** [WoltersKluwerPL/ng-spin-kit#44]
I'm sorry if this is the wrong place for this but... any reasons why the latest version available on [NPM](https://www.npmjs.com/package/ng2-spin-kit) is 1.0.3?

I was interested on using the new color attribute... 
Thanks in advance!

**Comment by Skyr** [comment]
I guess the artifact name changed at some point in time - https://www.npmjs.com/package/ng-spin-kit points to this repo as well and provides v5.1.1.

**Comment by mateuswetah** [comment]
Yeap, that was it. Thank you!
